In [1]:
#import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#import dataset
df = pd.read_excel("Simplified All samples.xlsx")

In [3]:
df.head()

Estimation value  Random sample value  Bmi Value  Rms value
0          150.9780                  140    24.1964   105.2693
1          150.9780                  147    24.1964   105.4302
2          150.4670                  125    23.6652   105.3727
3          151.7517                  135    24.9929   104.9116
4          151.2245                  156    24.4510   104.9896

In [4]:
df.shape

(31, 4)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Estimation value     31 non-null     float64
 1   Random sample value  31 non-null     int64  
 2   Bmi Value            31 non-null     float64
 3   Rms value            31 non-null     float64
dtypes: float64(3), int64(1)
memory usage: 1.1 KB


In [6]:
df.describe()

Estimation value  Random sample value  Bmi Value   Rms value
count         31.000000            31.000000  31.000000   31.000000
mean         153.407245           146.483871  26.744148  105.130329
std            3.972386            16.173787   4.104966    0.270287
min          148.896400           121.000000  22.031000  104.398200
25%          150.645000           133.000000  23.849800  104.950600
50%          151.751700           144.000000  25.103800  105.219400
75%          156.137500           158.000000  29.559900  105.340800
max          162.334000           178.000000  36.000000  105.512000

In [6]:
#splitting data into train & test
y= df.iloc[ : , :-3].values
X= df.iloc[ : , 2:4].values

In [7]:
X.shape

(31, 2)

In [8]:
y.shape

(31, 1)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.metrics import classification_report, confusion_matrix
clf = GaussianProcessRegressor(random_state=42)
clf.fit(X, y)

GaussianProcessRegressor(random_state=42)

In [11]:
# Make predictions using the test data
y_pred = clf.predict(X_test)

In [12]:
X_test

array([[ 29.3859 , 105.3408 ],
       [ 26.9127 , 105.4593 ],
       [ 30.8444 , 105.03311],
       [ 27.5872 , 105.2372 ],
       [ 23.3066 , 105.2613 ],
       [ 22.031  , 105.2194 ],
       [ 35.086  , 104.9986 ],
       [ 35.5998 , 104.9976 ],
       [ 22.3704 , 105.4754 ],
       [ 24.1964 , 105.2693 ],
       [ 24.451  , 104.9896 ]])

In [13]:
y_pred

array([[155.96999997],
       [153.59099997],
       [157.61089998],
       [154.24      ],
       [150.12280043],
       [148.89639983],
       [161.45499997],
       [161.94970004],
       [149.22099999],
       [150.97800041],
       [151.22449999]])

In [14]:
y_test

array([[155.97  ],
       [153.591 ],
       [157.6109],
       [154.24  ],
       [150.1228],
       [148.8964],
       [161.455 ],
       [161.9497],
       [149.221 ],
       [150.978 ],
       [151.2245]])

In [16]:
from sklearn.metrics import mean_squared_error
# Calculate the mean squared error
mse = mean_squared_error(y_test, y_pred)

In [17]:
# Print the mean squared error
print(mse)

3.5150761200784427e-14


In [18]:
from sklearn.metrics import mean_squared_error
import math
print('MSE: ',mean_squared_error(y_test, y_pred))
print('RMSE: ',math.sqrt(mean_squared_error(y_test, y_pred)))

MSE:  3.5150761200784427e-14
RMSE:  1.8748536263075158e-07


In [19]:
# R_Square and Adjusted R Square
import statsmodels.api as sm
X_addC = sm.add_constant(X)
result = sm.OLS(y, X_addC).fit()
print(result.rsquared, result.rsquared_adj)

0.9979845195283757 0.9978405566375455


In [20]:
score = clf.score(X_test,y_test)
print(score*100,'%')

99.99999999999983 %
